(function(f){function G(a){"$ignore"===a&&(e.define=y,y=null)}function H(a,b,c){c||(c=b,b=[]);g=0;z[a]=!0;p(b,function(){m[a]=c.apply(null,arguments)})}function p(){n.push(arguments);A()}function A(){var a,b,c,d,h,e,f,g;if(n.length){a=n;n=[];e={};k=[];for(b=a.length;b--;){d=[];f=!0;for(c=a[b][0].length;c--;)h=a[b][0][c],h in m?d[c]=m[h]:(e[h]||z[h]||(k.push(h),e[h]=!0),f&&(n.push(a[b]),f=!1));if(f){g=!0;try{a[b][1].apply(null,d)}catch(l){q(l,"runtime")}}}g?A():n.length&&!r&&(r=v(B,100))}}function B(){var a,
b,c,d,e=[];r=C(r);if(!g){w=C(w);for(a=k.length;a--;)d=k[a],t[d]?(k.splice(a,1),2>t[d]&&(t[d]++,e.push(d))):t[d]=1;g=k.length;e.length&&q(Error("Modules '"+e.join("', '")+"' failed to load"),"loadFailed");if(g){w=v(I,6E4);try{b=l.createElement("script"),b.src=J+"//s2.adform.net/stoat/587/s2.adform.net/load/v/0.0.106/e/"+m.$env.$hash()+"/i/"+m.$ignore+"/r:"+k.sort().join(":"),c=l.__gEBTN__("script")[0],b.onerror=K,c.parentNode.insertBefore(b,c)}catch(f){q(f,"script_insert")}}}}function K(){u("response_error",this.src)}function I(){g=
0;B()}function u(a,b,c){var d=[];Math.random()<(c||.03)&&(d.push((x.host||"//track.adform.net")+"/jslog/"),d.push("?src="),d.push(encodeURIComponent(a)),d.push("&msg="),d.push(encodeURIComponent(b)),a=D?new D(1,1):l.createElement("img"),a.src=d.join(""))}function q(a,b){var c=""+(a.stack||a);0>c.indexOf(a.message||"")&&(c=a+"\n"+c);v(function(){throw c;},0);u(b,c)}function E(){for(var a=arguments,b=0,c=a.length,d=[];b<c;b++)L(a[b])||d.push(a[b]);return d.length?F.apply(e,d):e.length}function L(a){function b(b){b.apply(null,
a.slice(1))}var c=a[0],d=m[c];d?b(d):p([c],b)}var y,F,r,w,k,e=f._adfq||(f._adfq=[]),l=f.document,v=f.setTimeout,C=f.clearTimeout,D=f.Image,x=f.Adform,J="https:"===(x&&(x.shost||"").split("/")[0]||f.location.protocol)?"https:":"http:",m={require:p,$boot:{window:f,require:p,rethrow:q,log:u,deprecate:function(a,b,c){var d=!1;return function(){d||(u("deprecate",b,c),d=!0);return a.apply(this,arguments)}}}},g=0,n=[],z={},t={};l.__gEBTN__=l.getElementsByTagName;(function(){var a;e.define?e.define=G:(F=
e.push,e.define=H,e.push=E,a=e.slice(),e.length=0,E.apply(e,a))})()})(window);
(function(a,h,c,b,e,I,G,H,E,C,D,F,B,d){
a(h,[c],function(c){c=c.window;var a=c.Adform||{},d=a.ET||{},b=a.RMB||{},e=b.Content||{};b.Type=b.Type||{};b.Content=e;a.ET=d;a.RMB=b;return c.Adform=a});
a(b,[c],function(V){function G(f){return f}function Y(){function f(){for(var u=1,b=t;u<k.length&&!k[u];u++)b=b.parent;try{return b==b.Function("return window")()}catch(a){}}function v(u,b){var a=b.charAt(0).toUpperCase()+b.slice(1);return l(u,b,"ms"+a,"moz"+a,"webkit"+a)}function l(a){for(var b=arguments,c=b.length;--c;)if(b[c]in a)return b[c]}function c(a,b){return 0<=(""+a).toLowerCase().indexOf(b.toLowerCase())}var e=V.window,d=e.document,w=d.documentElement,m=e.navigator,t=e.parent,g=
m.vendor,a=m.userAgent,x=d.createElement("div"),k=function(a){for(var b,c=100,e=a.top,d=[!0];--c&&a&&a!=e&&a!=a.parent;){try{b=!!(a=a.parent).Image}catch(f){b=!1}d.push(b)}return d}(e),n=e!=t,H=!n||k[1],B=!n||k[k.length-1],I=n&&f(),A=function(){var a,b=m.plugins,c=m.mimeTypes,d=e.ActiveXObject,f=26,b=b&&b["Shockwave Flash"]&&(!c||!c["application/x-shockwave-flash"]||c["application/x-shockwave-flash"].enabledPlugin)&&(b["Shockwave Flash"].version||b["Shockwave Flash"].description)||"";if(!b&&d)for(;6<=
f--;)try{a=new d("ShockwaveFlash.ShockwaveFlash."+f);6==f&&(a.AllowScriptAccess="always",b="WIN 6.0.21.0");try{b=a.GetVariable("$version").replace(/,/g,".")}catch(g){}break}catch(g){}return parseFloat(b.replace(/^.*?(\d+[\.,].*$)/,"$1").replace(/(^\d+\.)|\./g,"$1"))||0}(),y=10.3<=A&&!B,W=v(d,"hidden"),J=!!W,p=/MSIE|Trident/i.test(a),X=p&&("Microsoft Internet Explorer"===m.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))?parseFloat(RegExp.$1):-1,x=l(x,"addEventListener"),z=c(g,"apple computer"),
C=c(a,"ipad"),D=c(a,"iphone"),q=C||D,h;h=q&&(h=/\sos\s(\d+)_\d+/i.exec(a))&&(h=4<h[1]>>0);var E=c(g,"google"),K=!q&&c(a,"android"),L="ontouchstart"in d||"ontouchstart"in e,M=(z||E)&&/(chrome|crios)+\/[\d\.]+\s/i.test(a),F=/Firefox\/[\d\.]+/i.test(a),N=c(a,"opera"),g=c(a,"opr")&&c(g,"opera software"),r=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&z,a=p&&(c(a,"IEMobile")||c(a,"WPDesktop")),O=r&&!("webkitRequestAnimationFrame"in e),P="screenX"in e,Q="outerWidth"in e,R="mozInnerScreenX"in
e,w=w.msContentZoomFactor,S=!(!d.fireEvent||!d.attachEvent),G=v(e,"requestAnimationFrame"),y=y&&!r&&(!p||11<=X),T=q&&!r&&!m.standalone,U=l(e,"IntersectionObserver"),d=!!("srcdoc"in d.createElement("iframe")),d=!F&&d;return{result:[n,H,B,I,y,J,p,x,z,C,D,q,h,E,K,L,M,F,N,g,r,a,O,P,Q,R,w,S,!1,T,U,d],exports:{nop:function(){},access:k,frame:n,accParent:H,accTop:B,isolate:I,flashVersion:A,flInScreen:y,hidden:W,hasHidden:J,isIE:p,ieVersion:X,addEvent:x,isApple:z,isIPad:C,isIPhone:D,isIOS:q,isIOSF:h,isGoogle:E,
isAndroid:K,isTouch:L,isChrome:M,isFirefox:F,isOpera:N,isOperaWebkit:g,isSafari:r,isIEMobile:a,isSafari5OrLess:O,screenX:P,outerWidth:Q,mozInnerScreenX:R,msZF:w,ieDomEvents:S,reqAni:G,isRad:!1,isIOSWebView:T,intersectionAPI:U,hasSrcDoc:d,frame:n,accParent:H,accTop:B,isolate:I,flInScreen:y,hasHidden:J,isIE:p,addEvent:x,isApple:z,isIPad:C,isIPhone:D,isIOS:q,isIOSF:h,isGoogle:E,isAndroid:K,isTouch:L,isChrome:M,isFirefox:F,isOpera:N,isOperaWebkit:g,isSafari:r,isIEMobile:a,isSafari5OrLess:O,screenX:P,
outerWidth:Q,mozInnerScreenX:R,msZF:w,ieDomEvents:S,isRad:!1,isIOSWebView:T,intersectionAPI:U,hasSrcDoc:d}}}var A={$hash:function(){if(!t){for(var f=Y(),v=f.result,f=f.exports,l=[],c=0,e=v.length,d=0,e=e+(6-e%6)%6;c<e;c++)d=d<<1|!!v[c],5==c%6&&(l.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-".charAt(d)),d=0);for(c in f)A[c]=f[c];t=l.join("")}return t}},t;try{if(!Function("return ("+G+")(1)===1")())throw"Incorrect eval result";}catch(f){V.log("toString",f)}return A});
a(e,[c,b],function(m,d){var h=m.window,u=h.document,v=h.setTimeout;d.$hash();return function(a){var b,c,e,k,f,g,h=new Date;c=a.type;var n=a.placeId,w=/\.js(\?|$)/i,x=/\.swf(\?|$)/i,l=d.isIE,p=d.flashVersion,q=l&&10>d.ieVersion,l=!l&&21>p;b="standard"==a.type&&"flash"==a.subtype;var y=d.isSafari&&6.1<=d.safariVersion&&b,z=a.fVer||a.ADFVer||a.version,A=a.ADFPoliteSrc,r=a.sources||a.videoSources,t=["src","ADFFlash","ADFInitFlash","bsrc","ADFBuckup"];c=4==a.behavior?"Slider":c.charAt(0).toUpperCase()+
c.slice(1);b=["AdConstructor","types/"+c];if("Standard"==c){for(c=0;c<t.length;c++)(e=a[t[c]])&&(e.match(x)?k=e:e.match(w)?f=e:g=e);g&&q&&(f=0);g&&q&&(r=0);if(z>p||(g||f)&&(l||y))k=0;k?b.push("contents/FlashTag"):f?b.push("contents/HTML"):r&&b.push("contents/VideoTag");(!k&&!f&&g||A)&&b.push("contents/ImageTag")}m.require(b,function B(c){var b,d=c.cbuild;if(n)if(b=u.getElementById(n))a.placement=b.nextSibling||b.previousSibling,b.parentNode.removeChild(b),d(a);else if(1E4>new Date-h)v(function(){B(c)},
0);else throw Error("Failed to find placement");else d(a)})}});
a(I,[c,h],function(f,g){function e(a){return h(a).random()}function h(a){var e={random:k,int32:function(){var b,a,e=[0,2567483615];if(624<=c)for(a=c=0;624>a;a++)b=d[a]&2147483648|d[(a+1)%624]&2147483647,d[a]=d[(a+397)%624]^b>>>1^e[b&1];b=d[c++];b^=b>>>11;b^=b<<7&2636928640;b^=b<<15&4022730752;return(b^b>>>18)>>>0}},d=[],c;a||(a=Math.round(1E5*((new Date).getTime()+Math.random())));d[0]=a>>>0;for(c=1;a=c-1,624>c;c++)a=d[a]^d[a]>>>30,d[c]=(1812433253*((a&4294901760)>>>16)<<16)+1812433253*
(a&65535)+c,d[c]>>>=0;return e}function k(){return Math.floor(this.int32()/65535)}g.random=f.deprecate(e,"Adform.random is deprecated. Use h/random instead.");return e});
a(G,[c,h],function(e,a){function l(a,c){var f=c?9==c.nodeType?c:c.document:m;0<=a.indexOf('"')&&e.log("xss_detected",a);f.write('<script type="text/javascript" src="'+a+'">\x3c/script>')}function n(e){for(var c=a._prepareBannerDataCB,f={},d="ADFVideoCDN ADFDomainCDN ADFDomain VideoCDN ADFVideoCDNList ADFcmpgnID ADFmembID ADFtagID ADFafbanID ADFBanVer ADFBanVerBak ADFbanID ADFbanPlacID ADFUnloadID ADFClientSiteId ADFGeoData ADFGroupId ADFTemplateVersion ADFTemplateId ADF_ClickEvent".split(" "),
g=d.length-1;0<=g;g--)d[g]in h&&(f[d[g]]=h[d[g]]);var k=a.RMBData={clicktags:""};a._prepareBannerDataCB=function(){for(var b=d.length-1;0<=b;b--)d[b]in f&&(h[d[b]]=f[d[b]]);a.prepareBannerData(e);for(b in k)a.RMBData[b]="clicktags"!=b?k[b]:a.RMBData[b]+k[b];c&&c()};c||l(a.scriptBase+"bootstrap/Adform.BannerData.js?v="+a.cache)}var h=e.window,m=h.document;a.host&&(ADFDynamicDomain=a.host+"/banners/");a.shost&&(ADFTemplateDomain=a.shost+"/banners/");a.ENV={akamaiHost:("https:"==m.location.protocol?
"https://":"http://")+"adformvod-vh.akamaihd.net/i/Banners"};a.Log=a.Log||{sendMessage:e.log};a.loadResource=a.loadResource||l;a.prepareBannerData=a.prepareBannerData||n;return{loadResource:a.loadResource,prepareBannerData:a.prepareBannerData}});
a(H,function(){function f(a){a=a||"";var b=a.split(";oobclicktrack=");b.shift();b.length&&(this.tracks=b);a=a.split("?");this._base=a.shift();this._parts=a.join("?").split(";");this.append=[]}function g(a,b,c){var d=a.length;b+="=";var e,f=b.length;for(c||(b=b.toLowerCase());d--&&(e=a[d].slice(0,f),c||(e=e.toLowerCase()),e!==b););return d}var h=Object.prototype.hasOwnProperty,e=f.prototype;e.copy=function(){var a,b=new f;for(a in this)h.call(this,a)&&(b[a]=this[a]&&this[a].slice?this[a].slice(0):
this[a]);return b};e.get=function(a,b){var c=this._parts,d=g(c,a,b);if(~d)return c[d].slice(a.length+1)};e.set=function(a,b,c){var d=this._parts;c=g(d,a,c);0>c?d.push(a+"="+b):d[c]=d[c].slice(0,a.length+1)+b;return this};e.unset=function(a,b){var c=this._parts,d=g(c,a,b);~d&&c.splice(d,1);return this};e.toString=function(){return this._base+"?"+this._parts.join(";")+this.append.join("")};return f});
a(E,[c,b,h,e,I,G,H],function(y,B,f,T,C,e,U){function w(){var a,b;if(r)return r;this.banners={};this.compoundBanners={};try{h.body||h.write("<html><body></body></html>")}catch(c){}a=n.browserLanguage||n.language||0;b=this.getWin();this.settings=[escape(n.systemLanguage||a),escape(a),u?u.width+"X"+u.height:0,B.flashVersion,50*Math.round(b.w/50),50*Math.round(b.h/50),u?u.colorDepth:0,8,3,7,this.hasIframeSanbox()].join("|")}function L(a){var b=
a.placeId="+ADFP"+a.adfxid;h.write('<i id="'+b+'" style="display:none"></i>');y.require(["types/ThirdParty"],function(b){b(a)})}function M(a){var b,c,d;if(a=a||f.BannerList&&f.BannerList.shift()||f.RMBData)b=a.type,c=a.behavior,d=a.adfxid||a.ADFid,a._beforeScript=f._beforeScript,f._beforeScript=!1,{standard:1,expanding:1,singleExpanding:1}[b]&&![0,0,0,1,1][c]&&(a.placeId="+ADFP"+d,b=r.banners[d],h.write('<div id="'+a.placeId+'"'+(b.singleTag?"":' style="width:'+b.width+"px;height:"+b.height+'px;"')+
'></div><i style="display:none"></i>')),T(a)}function D(a,b,c){var d=(c=c||h).createElement("div");d.innerHTML='<iframe src="'+a+'" allowtransparency="true" webkitallowfullscreen mozallowfullscreen allowfullscreen marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" style="'+b+'"></iframe>';c.body.appendChild(d.removeChild(d.firstChild))}function N(a){var b,c,d,e=/\/adfscript/,l=f.ADFIframe&&{src:g.location.href.replace(/cpjs=2/,"cpjs=0")};if(!l)for(b=h.getElementsByTagName("script"),
c=b.length;c--&&!l;)(d=b[c]).src&&d.src.match(e)&&-1<d.src.indexOf(a)&&(l=d);return l||{}}function V(a){var b,c;c=g._adform&&g._adform.tagFrame;var d=a;if("undefined"!=typeof a.URL){try{b=g.top.location.href.split("#")[0]}catch(e){b=c||g,c=(c=b.location.ancestorOrigins)&&c[c.length-1],b=b.document.referrer||c}b=b?z(b):a.CREFURL;d=new U(a.URL);d.append.push("&CREFURL="+b);d.CREFURL=b;d.STUBFILE=a.STUBFILE;d.BN=a.BN;d.ROTSEQ=a.ROTSEQ}return d}function E(a,b){try{if(a){(b=b||[]).push(a);for(var c=0;c<
a.frames.length;c++)E(a.frames[c],b);return b}}catch(d){}}function O(a){return C(a+this.id)}function P(a){try{return a.Adform&&a.Adform.ADFUtilInstance}catch(b){}}function F(){return(new Date).getTime()}function Q(a){try{return W(a)}catch(b){return a}}var r,m,G,H,x,I,g=y.window,h=g.document,n=g.navigator,u=g.screen,X=g.setTimeout,J=g.Image,Y=Object.prototype.hasOwnProperty,A=e.loadResource,z=g.encodeURIComponent,W=g.decodeURIComponent,R=f.cache,K=[];e=w.prototype;var S={webkitVisibilityState:"webkitvisibilitychange",
mozVisibilityState:"mozvisibilitychange",msVisibilityState:"msvisibilitychange",visibilityState:"visibilitychange"};if(f.ADFBannerUtils)return f.ADFBannerUtils;for(x in S)x in h&&(G=x,H=S[x]);e.getCompoundBannerInfo=function(a){return this.compoundBanners["c"+a]||null};e.createBanner=function(a){function b(a){var b=a.url;"stubFileExists"in p||(a.helper&&X(function(){y.log("StubFileError","Cref: "+t+" > Adfserve: "+k+" > bn: "+v)},100),(p.stubFileExists=a.exists)?(b=Q(b),D(f.scriptBase+"iframe/recache.html?bv="+
R,"position:absolute;width:10px;height:10px;left:-9999px;top:-9999px"),D(b+"#"+R+"#"+N(v).src,"position:absolute;top:0;left:0;width:100%;height:100%",g._adform&&g._adform.tagFrame&&g.parent.document)):((c=f.RMB)&&(c=c.AdConstructor)&&(c=c.cbuild)||(f.RMB=f.RMB||{},f.RMB.AdConstructor={build:M},f.thirdPartyCB=L),A(k)))}var c,d,e,l,k,q=this,m=q.getTagID(),p=q.addNewBanner(m,"undefined"==typeof f.ADFIframe?0:1);a=p.params=V(a,q);l=a.get("compoundSeqNo");var v=a.BN,n=q.getCompoundBannerInfo(v),u=q.getPropByBn("smid",
v),w=a.ROTSEQ,t=a.CREFURL,r=a.STUBFILE,x;a.tracks&&(p.OOBClickTracks=a.tracks);a.get("singleTag")&&(p.singleTag=!0,l=l||1,a.set("compoundSeqNo",l));p.compoundSeqNo=l;"prerender"==h[G]&&(a.set("hid",2),p.prerender=!0,h.addEventListener(H,function(){"prerender"!=h[G]&&p.prerender&&(h.removeEventListener(H,arguments.callee,!1),q.registerImpression(p))},!1));l&&(l=q.getRotSeed(),d=l.gen(v),l.compound[v]?e=l.compound[v]:w&&(l.compound[v]=w));a.set("js",1);a.set("adfxid",m);a.set(Math.floor(11E3*Math.random())+
";set",q.settings);d&&a.set("rotseed",d);e&&a.set("rotseq",z(e));n&&a.set("rotseqno",n.replace("r",""));u&&a.set("smid",u);f.CDNHost&&a.set("cdnhost",z(f.CDNHost));k=a.toString();t&&r&&!f.ADF_STUB&&(t=Q(t).replace(/(:\/\/[^\/]+).*/,"$1"),x=r.HOST?t.split("/")[2]===r.HOST&&q.needStubFile(t):q.needStubFile(t));x?(f.stubFile=b,d=f.shost+"/adfstub/?url="+z(t+r.PATH),A(d),A(f.scriptBase+"extra/StubHelper.js?bv="+f.cache)):(f.ADF_STUB&&y.log("adfstub",t,1),(c=f.RMB)&&(c=c.AdConstructor)&&(c=c.cbuild)||
(f.RMB=f.RMB||{},f.RMB.AdConstructor={build:M},f.thirdPartyCB=L),A(k));return p};e.addNewBanner=function(a,b){return this.banners[a]={id:a,type:b,adfserveLoadTime:F()}};e.copyBanner=function(a,b){var c,d=this.banners[a];if(d=d&&d.params||null){d=d.copy();for(c in b)Y.call(b,c)&&d.set(c,b[c]);d=this.createBanner(d)}return d};e.wipeOutBanner=function(a){var b=this.banners[a];b&&(m&&(m.id=C(),m.compound&&delete m.compound[b.bn]),delete this.compoundBanners["c"+b.bn],delete this.banners[a])};e.addBannerAttribute=
function(a,b,c){(a=this.banners[a])&&(a[b]=c)};e.getTagID=function(){var a=this.getRotSeed();a.xId||(a.xId=0);return++a.xId+"x"};e.getRotSeed=function(){var a,b,c,d,e;if(!m&&!I){I=!0;try{for(a=E(g.top),b=0,c=a.length;b<c;b++)if(d=a[b],d!=g&&(e=P(d))&&e.getRotSeed){m=e.getRotSeed();break}}catch(f){}m?m.gen=O:m={compound:{},id:C(),gen:O}}I=!1;return m};e.getFlashVersion=y.deprecate(function(){return B.flashVersion},"Utils_getFlash");e.getWin=function(){var a=h.documentElement,b=h.body;return{w:g.innerWidth||
a&&a.clientWidth||b&&b.clientWidth,h:g.innerHeight||a&&a.clientHeight||b&&b.clientHeight}};e.getSettings=function(){return this.settings};e.firePixel=function(a){("undefined"==typeof J?h.createElement("img"):new J).src=a};e.fireTargAdPixel=function(a){var b=this.TargAd||{};b[a]||((this.TargAd=b)[a]=!0,a=a.replace("{gmtr}",Math.floor(9999999999*Math.random())).replace("{gmttzd}",(new Date).getTimezoneOffset()),this.firePixel(a))};e.registerImpression=function(a){var b,c;a&&a.prerender&&(b=a.params.copy(),
b.set("hid",1),a.rotseqno&&b.set("rotseqno",a.rotseqno),c=h.createElement("script"),c.src=b.toString(),c.type="text/javascript",h.body.appendChild(c),delete a.prerender)};e.addCompoundBannerInfo=function(a,b){this.compoundBanners["c"+a]="r"+b};e.setBannerRegisteredStatus=function(a){var b,c,d=this.banners[a];if(d){var e=F(),g=e-d.adfserveLoadTime,k=parseInt(d.serverTime,10),h=f.ADFEventsInstance;d.adfserveLoadTime=g;k&&(k+=Math.round(.5*g),d.serverTime=k,d.timeDiff=k-e);d.registered=1;this.sendLoadMetrics(a);
if(d.singleTag&&1==d.compoundSeqNo)for(b=2,c=d.syncMembersCount;b<=c;b++)this.copyBanner(a,{compoundSeqNo:b,compoundImpr:0});try{for(h&&h.register(d),b=0,c=K.length;b<c;b++)K[b].call(this)}catch(m){}}};e.onBannerRegisteredStatus=function(a){K.push(a)};e.hasIframeSanbox=function(){var a=this._sandbox;if("number"!=typeof a){a=1;try{g.top.document.getElementById,a=0}catch(b){}this._sandbox=a}return a};e.getPropByBn=function(a,b){var c,d,e=this.banners;for(c in e)if(d=e[c],d.bn==b&&a in d)return d[a]};
e.now=F;e.needStubFile=function(a){var b=g.$sf,c=g.parent,d=this._stub,e=g._adform&&g._adform.tagFrame,f=/^https?:/,k=g.location.protocol;if(null==d){d=!(g==c||g.inDapMgrIf||g.inDapIF||g.inFIF||b&&b.ext);!d&&e&&(d=!0,c=e.parent);if(d)try{c.document.getElementById,d=!1}catch(h){}d&&(k=k.match(f)?k:null,B.accParent&&!k&&(k=c.location.protocol,k=k.match(f)?k:null),d=a.split("/")[0]===k);this._stub=d}return d};e.getAdfscript=N;e.getUnloadId=function(a){try{for(var b,c,d,e,f=E(g.top),h=f.length;h--;)for(d in b=
(c=P(f[h]))&&c.banners,b)if(e=b[d],e.bn==a&&1==e.compoundSeqNo)return e.unloadID}catch(m){}};e.sendLoadMetrics=function(a){a=this.banners[a];var b=g.ADFGeoData;!a.metricsSent&&"string"==typeof b&&.1>Math.random()&&(b=b.split(";"),3==b.length&&((new J).src=f.host+"/jsmetrics/?adfserve="+a.adfserveLoadTime+"&sid="+b[2]+"&rid="+b[1]+"&cid="+b[0]));a.metricsSent=!0};e.loadFrame=D;e.ADFCreateObjectCallback=function(a,b){return function(){b.apply(a,arguments)}};e.eventRegister=function(){};e.getPosition=
function(a){for(var b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b};e.getScrollXY=function(){var a=h.body,b=h.documentElement,c={x:0,y:0};"number"==typeof g.pageYOffset?(c.y=g.pageYOffset,c.x=g.pageXOffset):a&&(a.scrollLeft||a.scrollTop)?(c.y=a.scrollTop,c.x=a.scrollLeft):b&&(b.scrollLeft||b.scrollTop)&&(c.y=b.scrollTop,c.x=b.scrollLeft);return c};e.getBrowser=function(){try{var a=n.userAgent;return~n.appVersion.indexOf("MSIE")&&0>a.indexOf("Opera")?"MSIE":~a.indexOf("Safari")?
"Safari":~a.indexOf("Opera")?"Opera":~a.indexOf("Netscape")?~n.product.indexOf("Gecko")&&(~n.vendor.indexOf("Firefox")||~a.indexOf("Firefox"))?"Firefox":"Netscape":void 0}catch(b){}};f.ADFUtilInstance=r=new w;return f.ADFBannerUtils=w.getInstance=w});
a(C,[c,h,E],function(a,e,c){var l=Object.prototype.hasOwnProperty,m=a.window,n=m.document;a={Initialized:!1,InitTime:(new Date).getTime(),Host:e.host||("https:"==n.location.protocol?"https://":"http://")+"track.adform.net",callbacks:[],sendEvent:function(p,f,a,c,h){var d,g,b,k;g=Math.round(((new Date).getTime()-this.InitTime)/1E3);b=q.banners[p];k=e.adRegister&&e.adRegister[p];try{this.notifyAboutEvent.apply(this,arguments)}catch(l){}if(!b&&k)d=k.sendEvent(f,a,c,h);
else if(b&&b.isEventsEnabled){d=b.bn;!b._imprID&&1<b.compoundSeqNo&&(b._imprID=q.getUnloadId(d)||b.unloadID);g=["bn",d,"event",f,"time",(0>g?0:3600<g?3600:g)+"","banner",b.ban,"innerbanner",b.innerban,"asset",a,"name",c,"imprid",b._imprID||b.unloadID,"icid",b.cookieID,"adxvars",b.adxvars,"rnd",Math.floor(1E9*Math.random())];b=0;for(d=[];b<g.length;b+=2)(k=g[b+1])&&d.push(g[b]+"="+encodeURIComponent(k));d=this.Host+"/Serving/Event/?"+d.join("&")+(h||"");(m.Image?new m.Image(1,1):n.createElement("img")).src=
d}return d},Initialize:a.deprecate(function(){this.Initialized=!0},"initEvents",1),registerCallback:function(a,f){"function"==typeof a&&this.callbacks.push([a,f])},unregisterCallback:function(a){var f=this.callbacks,c=f.length;if("function"==typeof a)for(;c--;)f[c][0]==a&&f.splice(c,1)},notifyAboutEvent:function(){for(var a=this.callbacks.slice(),c=0,e=a.length;c<e;c++)a[c][0].apply(a[c][1]||this,arguments)}};var q=c();if(c=e.Events){for(var h in a)l.call(a,h)&&!l.call(c,h)&&(c[h]=a[h]);c.sendEvent=
a.sendEvent}else c=e.Events=a;e.ADFEvents2||(e.ADFEvents2=c);return a});
a(D,[c,h],function(g,b){function d(c){try{var e=c.URL,d=c.BN,h,a,m,k;c=/\/adfscript/;var l=b.ADFIframe&&{src:r.location.href.replace(/cpjs=2/,"cpjs=0")};if(!l)for(a=n.getElementsByTagName("script"),m=a.length;m--&&!l;)(k=a[m]).src&&k.src.match(c)&&-1<k.src.indexOf(d)&&(l=k);h=l||{};var f=n.createElement("div");a=h;var p,t,q,u,e=e.split(";");e[0]+=";srctype=6";for(e=e.join(";");a;)p="BODY"==a.nodeName,t="HEAD"==a.nodeName,a=!(p||t)&&a.parentNode;p?(q=h.parentNode,u=h):q=n.body;f.innerHTML=
'<a href="'+b.host+"/C/?bn="+d+';C=0"><img src="'+e+'"></a>';q.insertBefore(f.firstChild,u||null);g.log("fallback",d)}catch(v){g.rethrow(v,"fallback_error")}}var f,r=g.window,n=r.document;g.require(["$ignore"],function(){var c=b.ADFBannerParams;f||(b.ADFUtilInstance||(b.ADFUtilInstance={}),b.ADFBanner||(b.ADFBanner=d),d(c&&c.length?c.shift():b.ADFBannerData))});return{cancel:function(){f=!0},write:d}});
a(F,[c,h,E],function(t,g,u){function m(c){for(var e=0,G=c.length;e<G;e++){var a=c[e],b=void 0,v=void 0,d,m=g.scriptBase,p=g.cache,h=a.xId,w=a.externalScripts,x=a.trackingPixelUrls,f=a.banner;d=f.backup;var k=f.type,n=f.clickUrls,u=a.visibility.testMode,y=a.trackingIframeUrls,z=a.geoLocation,l={},E=a.csImpressionUrl,A=q.banners[h];w&&(b=w.before,v=w.after);b&&(B(b),g._beforeScript=!0);if(y)for(b=y.length;b--;)q.loadFrame(y[b],"display:none");A&&(C(H,a,A),A.isDSPTag=
"dsp"===a.impressionType,q.setBannerRegisteredStatus(h));if("thirdparty"===k.type){g.thirdPartyCB&&g.thirdPartyCB({adfxid:h});try{F.write(a.banner.script)}catch(D){t.rethrow(D,"thirdPartyWrite")}E&&((new r.Image).src=E)}else if("standard"!=k.type||"image"!=k.subType&&"flash"!=k.subType&&"html"!=k.subType)t.log("rollback",f.tagId+" banner not rendered",1);else{b=f.properties;h={type:k.type,subtype:k.subType,landingPageTarget:b.landingTarget,ADFFlash:f.asset&&f.asset.url||f.url,ADFBuckupClickURL:d&&
d.clickUrl||a.clickUrl,width:f.size.width,height:f.size.height,ADFid:h,ADFban:f.tagId,bannerAlign:b.align,clicktags:l,flashvars:l,defaultClickTAG:n[0]&&n[0].name,css:m+"assets/css/Adform.RMB.css?bv="+p,quality:b.quality,wmode:b.wMode,fVer:b.flashVersion};d&&(h.ADFBuckup=d.url);d=0;for(b=n.length;d<b;d++)l[n[d].name]=encodeURIComponent(n[d].url);C(I,a,l);l.domain=encodeURIComponent(a.staticContentUrl);l.bn=f.tagId;l.geo=[z.city.id,z.region.id,z.country.id].join(";");g.RMB.AdConstructor.build(h)}if(x)for(d=
0,b=x.length;d<b;d++)q.fireTargAdPixel(x[d]);v&&B(v);u&&B([m+"unload/Adform.Inscreen.js?"+p])}}function p(){D.apply(this,arguments);m(arguments)}function B(c){for(var e=0;e<c.length;e++)F.write('<script src="'+c[e]+'">\x3c/script>')}function C(c,e,g){var a,b;for(a in c)b=c[a],"string"===typeof b?null!=e[a]&&(g[b]=e[a]):e[a]&&C(b,e[a],g)}var r=t.window,F=r.document,D=Array.prototype.push,q=u(),H={visitor:{cookieId:"cookieID"},csImpressionUrl:"csImpressionUrl",interactionId:"unloadID",visibility:{sendUnload:"sendUnloadData",
area:"visibilityArea",time:"visibilityTime"},serverTime:"serverTime",banner:{id:"ban",version:"bannerVersion",template:{dcoEngineId:"dcoEngineId"},size:{width:"width",height:"height"},rotationSeqenceNumber:"rotseqno",smId:"smid",tagId:"bn",campaignId:"pm",membershipId:"ms",bannerPlacementId:"bnpl",isEventEnabled:"isEventsEnabled"},isAdNoticeEnabled:"adNotice",publisher:{adxvars:"adxvars",publisherUnloadData:"publisherUnloadData",visibility:{area:"publisherVisibilityArea",time:"publisherVisibilityTime"}},
dsp:{inventorySourceId:"rtbInventorySourceId",requestId:"rtbReqId",rtbdata:"rtbdata",isUnloadUfcEnabled:"ufcEnabled",rtbwp:"rtbwp"}},I={banner:{clientSiteId:"cid",template:{groupId:"gid",version:"tv",id:"tid"},version:"bv",campaignId:"ADFcmpgnID",membershipId:"ADFmembID",id:"ADFbanID",bannerPlacementId:"ADFbanPlacID",properties:{wMode:"wmode"}},xId:"ADFid",interactionId:"unloadID",trackingSetupId:"trackingSetupId"};return function(){var c=r.adfjsonbanners;c?(c.push=p,m(c)):(c=[],c.push=p,r.adfjsonbanners=
c)}});
a(B,[c,h,C,D,E,F],function(g,a,c,f,h,k){function d(){var b=a.ADFBannerParams,e=b&&b.length?b.shift():a.ADFBannerData;if(e)try{h().createBanner(e)}catch(c){g.rethrow(c,"create_banner"),f.write(e)}b&&b.length&&d()}a.ADFBanner||(a.ADFBanner=d,a.ADFBanner());k();c.IE=9;f.cancel();return d});
a(d,function(){return"8IP4AAAAIAA"});
})(_adfq.define,"Adform","$boot","$env","$main","h/random","bootstrap/Global","bootstrap/URL","bootstrap/Utils","bootstrap/Events","bootstrap/Fallback","bootstrap/adfjsonbanners","bootstrap/Banner","$ignore");